apiVersion: v1
kind: ServiceAccount
metadata:
  name: gmp-ds-syncer
  namespace: monitoring
  annotations:
    iam.gke.io/gcp-service-account: gmp-ds-syncer@mohan-sre-assessment-20261001.iam.gserviceaccount.com
automountServiceAccountToken: true